# Generated by Django 5.2.17 on 2026-09-19 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="invoice_id",
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
