# Generated by Django 5.2.17 on 2026-09-19 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_alter_order_invoice_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="invoice_id",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
