# Generated by Django 5.2.17 on 2026-10-02 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_alter_order_invoice_id"),
        ("subscriptions", "0002_studentsubscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="tariff",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="subscriptions.tariffplan",
            ),
            preserve_default=False,
        ),
    ]
