# Generated by Django 5.2.17 on 2026-09-14 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0003_alter_student_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="lessons_price",
            field=models.DecimalField(decimal_places=2, default=600, max_digits=10),
        ),
    ]
