# Generated by Django 5.2.17 on 2026-09-15 14:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0004_student_lessons_price"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="student",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("group", "name"),
                name="unique_student_in_group",
            ),
        ),
        migrations.AddConstraint(
            model_name="student",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("teacher", "name"),
                name="unique_student_in_teacher",
            ),
        ),
    ]
