# Generated by Django 5.2.17 on 2026-09-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0005_student_unique_student_in_group_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grouplesson",
            name="attendance_list",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
