# Generated by Django 5.2.17 on 2026-09-19 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0007_group_unique_group_in_teacher"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="lessons_count",
        ),
        migrations.RemoveField(
            model_name="student",
            name="lessons_price",
        ),
    ]
