# Generated by Django 5.2.17 on 2026-09-19 20:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("schedule", "0007_group_unique_group_in_teacher"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TariffPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "tariff_type",
                    models.CharField(
                        choices=[
                            ("per_lesson", "Per Lesson (Flexible)"),
                            ("package", "Fixed Package / Subscription"),
                        ],
                        default="package",
                        max_length=20,
                    ),
                ),
                (
                    "price_per_lesson",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("default_lessons_amount", models.PositiveIntegerField(default=1)),
                ("duration_days", models.PositiveIntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "students",
                    models.ManyToManyField(
                        blank=True,
                        related_name="available_tariffs",
                        to="schedule.student",
                    ),
                ),
                (
                    "teachers",
                    models.ManyToManyField(
                        blank=True,
                        limit_choices_to={"is_teacher": True},
                        related_name="tariffs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
